// <auto-generated />
using MainServer.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MainServer.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20211108001858_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("MainServer.Models.Lecturer", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("FIO")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("MainServer.Models.Student", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("FIO")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<string>("LecturerUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.HasIndex("LecturerUsername");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MainServer.Models.Student", b =>
                {
                    b.HasOne("MainServer.Models.Lecturer", null)
                        .WithMany("Students")
                        .HasForeignKey("LecturerUsername");
                });

            modelBuilder.Entity("MainServer.Models.Lecturer", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
