// <auto-generated />
using MainServer.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MainServer.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("LecturerStudent", b =>
                {
                    b.Property<string>("LecturersUsername")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentsUsername")
                        .HasColumnType("TEXT");

                    b.HasKey("LecturersUsername", "StudentsUsername");

                    b.HasIndex("StudentsUsername");

                    b.ToTable("LecturerStudent");
                });

            modelBuilder.Entity("MainServer.Models.Lecturer", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("FIO")
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("MainServer.Models.Student", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("FIO")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Username");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("LecturerStudent", b =>
                {
                    b.HasOne("MainServer.Models.Lecturer", null)
                        .WithMany()
                        .HasForeignKey("LecturersUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainServer.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
